# Generated by Django 4.1.7 on 2024-04-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0013_alter_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='app_meu_pacote.apartamento'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
